export const ADD_TO_CART = "ADD_TO_CART"
export const UPDATE_TO_CART = "UPDATE_TO_CART"
export const DELETE_FROM_CART = "DELETE_FROM_CART"
export const DEC_FROM_CART = "DEC_FROM_CART"
export const REMOVE_CART = "REMOVE_CART"
